PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?birth
WHERE
{
    ?person foaf:name ?name .
    ?person dbo:birthDate ?birth .
    ?person a dbo:BasketballPlayer .
    ?person dbp:nba ?nba .
    FILTER ( datatype(?birth ) = xsd:date) .
}