PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?url
WHERE
{
    ?person a dbo:BasketballPlayer .
    ?person dbp:nba ?nba .
    ?person foaf:isPrimaryTopicOf ?url
}
GROUP BY $url